"""add 3

Revision ID: 5ebbd6c2e315
Revises: 5a343310760c
Create Date: 2026-07-10 19:20:07.974450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5ebbd6c2e315'
down_revision: Union[str, Sequence[str], None] = '5a343310760c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sms_transactions', 'transaction_id',
               existing_type=sa.VARCHAR(length=60),
               type_=sa.String(length=100),
               nullable=True)
    op.alter_column('sms_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('sms_transactions', 'source',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=50),
               nullable=True)
    op.alter_column('sms_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=True)
    op.alter_column('sms_transactions', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('sms_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('sms_transactions', 'bank_transaction_id')
    op.drop_column('sms_transactions', 'telegram_user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_transactions', sa.Column('telegram_user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('sms_transactions', sa.Column('bank_transaction_id', sa.VARCHAR(length=60), autoincrement=False, nullable=True))
    op.alter_column('sms_transactions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('sms_transactions', 'is_used',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('sms_transactions', 'transaction_type',
               existing_type=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('sms_transactions', 'source',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=30),
               nullable=False)
    op.alter_column('sms_transactions', 'amount',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               nullable=False)
    op.alter_column('sms_transactions', 'transaction_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=60),
               nullable=False)
    # ### end Alembic commands ###
