"""add telegram user to sms transactions

Revision ID: 7e492cb15802
Revises: 79c88897cb36
Create Date: 2026-07-10 18:03:24.842981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e492cb15802'
down_revision: Union[str, Sequence[str], None] = '79c88897cb36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_transactions', sa.Column('telegram_user_id', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_transactions', 'telegram_user_id')
    # ### end Alembic commands ###
